apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solaradocs-ingress
  namespace: solaradocs
spec:
  rules:
    - host: solaradocs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8000
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000