from django.urls import path, include
from django.conf import settings
from . import views
from . import views_admin
from . import views_import

_ADMIN = settings.ADMIN_PANEL_PATH

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('setup/', views.setup, name='setup'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('accounts/', include('allauth.urls')),
    path('changeroles/', views.change_roles, name='change_roles'),
    path('about/', views.about, name='about'),
    path('collaborations/', views.collaborations, name='collaborations'),
    path('deleteproject/', views.delete_project, name='delete_project'),
    path('handlepending/', views.handle_pending, name='handle_pending'),
    path('', include('django_prometheus.urls'), name='django_prometheus'),
    path('docs/', views.docs, name='docs'),
    path('password-reset/', views.password_reset, name='password_reset'),
    path('password-reset/', views.password_reset, name='password_reset'),
    path('password-reset/send', views.password_reset_send, name='password_reset_send'),
    path('password-reset/verify', views.password_reset_verify, name='password_reset_verify'),
    path('password-reset/confirm', views.password_reset_confirm, name='password_reset_confirm'),
    path('changelog/', views.changelog, name='changelog'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('addpeople/', views.add_people, name='add_people'),
    path('deleteuser/', views.deleteuser, name='deleteuser'),
    path('api/project/<int:project_id>/backups', views.list_project_backups, name='list_project_backups'),
    path('api/project/<int:project_id>/backups/<int:backup_id>/revert', views.revert_backup, name='revert_backup'),
    path('api/project/<int:project_id>/pending/<int:pending_id>/diff', views.pending_diff, name='pending_diff'),
    path('api/project/<int:project_id>/backups/<int:backup_id>/diff', views.backup_diff, name='backup_diff'),
    path('api/project/<int:project_id>/toggle-backups', views.toggle_backups, name='toggle_backups'),
    path('api/project/<int:project_id>/rename', views.rename_project, name='rename_project'),
    path('api/project/<int:project_id>/collaborators', views.get_collaborators, name='get_collaborators'),
    path('logout/', views.logout, name='logout'),
    path('create-checkout-session/', views.create_checkout_session, name='create-checkout-session'),
    path('success/', views.success, name='success'),
    path('buy/', views.buy, name='buy'),
    path('gen/token', views.get_oauth_token, name='generate_token'),
    path('webhook/stripe/', views.stripe_webhook, name='stripe_webhook'),
    path('api/project/<int:project_id>/documents', views.get_documents, name='get_documents'),
    path('api/project/<int:project_id>/documents/<int:doc_id>', views.get_document, name='get_document'),
    path('api/project/<int:project_id>/documents/add', views.add_document, name='add_document'),
    path('api/project/<int:project_id>/documents/<int:doc_id>/save', views.save_document, name='save_document'),
    path('api/project/<int:project_id>/documents/<int:doc_id>/rename', views.rename_document, name='rename_document'),
    path('api/project/<int:project_id>/documents/<int:doc_id>/delete', views.delete_document, name='delete_document'),
    path('api/project/<int:project_id>/teams', views.get_teams, name='get_teams'),
    path('api/project/<int:project_id>/audits', views.get_audits, name='get_audits'),
    path('api/project/<int:project_id>/pending', views.get_pending_edits, name='get_pending_edits'),
    path('api/project/<int:project_id>/pending-actions', views.get_pending_actions, name='get_pending_actions'),
    path('api/project/<int:project_id>/teams/add', views.create_team, name='create_team'),
    path('api/project/<int:project_id>/teams/<int:team_id>/update', views.update_team, name='update_team'),
    path('api/project/<int:project_id>/teams/<int:team_id>/delete', views.delete_team, name='delete_team'),
    path('api/project/<int:project_id>/teams/<int:team_id>/members/add', views.add_team_member, name='add_team_member'),
    path('api/project/<int:project_id>/teams/<int:team_id>/members/remove', views.remove_team_member, name='remove_team_member'),
    path('api/project/<int:project_id>/teams/<int:team_id>/members/role', views.update_team_member_role, name='update_team_member_role'),
    path('api/project/<int:project_id>/teams/<int:team_id>/members/review', views.update_team_member_review, name='update_team_member_review'),
    path('api/project/<int:project_id>/viewer-access', views.get_viewer_access, name='get_viewer_access'),
    path('api/project/<int:project_id>/viewer-access/save', views.save_viewer_access, name='save_viewer_access'),
    path('api/project/<int:project_id>/viewer-documents', views.get_viewer_documents, name='get_viewer_documents'),
    path('api/project/<int:project_id>/viewer-document/<int:doc_id>/content', views.get_viewer_document_content, name='get_viewer_document_content'),
    path('profile/', views.profile, name='profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('cancel-subscription/', views.cancel_subscription, name='cancel_subscription'),
    path('delete-account/', views.delete_account, name='delete_account'),
    path(f'{_ADMIN}/', views_admin.admin_panel, name='admin_panel'),
    path(f'{_ADMIN}/update-user/', views_admin.admin_update_user, name='admin_update_user'),
    path(f'{_ADMIN}/delete-user/', views_admin.admin_delete_user, name='admin_delete_user'),
    path(f'{_ADMIN}/toggle-user-active/', views_admin.admin_toggle_user_active, name='admin_toggle_user_active'),
    path(f'{_ADMIN}/toggle-superuser/', views_admin.admin_toggle_superuser, name='admin_toggle_superuser'),
    path(f'{_ADMIN}/delete-project/', views_admin.admin_delete_project, name='admin_delete_project'),
    path(f'{_ADMIN}/transfer-project/', views_admin.admin_transfer_project, name='admin_transfer_project'),
    path(f'{_ADMIN}/add-changelog/', views_admin.admin_add_changelog, name='admin_add_changelog'),
    path(f'{_ADMIN}/update-changelog/', views_admin.admin_update_changelog, name='admin_update_changelog'),
    path(f'{_ADMIN}/delete-changelog/', views_admin.admin_delete_changelog, name='admin_delete_changelog'),
    path(f'{_ADMIN}/broadcast-announcement/', views_admin.admin_broadcast_announcement, name='admin_broadcast_announcement'),
    path(f'{_ADMIN}/dismiss-alert/', views_admin.admin_dismiss_alert, name='admin_dismiss_alert'),
    path(f'{_ADMIN}/create-promo/', views_admin.admin_create_promo, name='admin_create_promo'),
    path(f'{_ADMIN}/delete-promo/', views_admin.admin_delete_promo, name='admin_delete_promo'),
    path('api/project/<int:project_id>/invite-codes', views.list_invite_codes, name='list_invite_codes'),
    path('api/project/<int:project_id>/invite-code/generate', views.generate_invite_code, name='generate_invite_code'),
    path('api/project/<int:project_id>/invite-code/<int:code_id>/delete', views.delete_invite_code, name='delete_invite_code'),
    path('api/invite-code/redeem', views.redeem_invite_code, name='redeem_invite_code'),
    path('redeem-promo/', views.redeem_promo, name='redeem_promo'),

    path('api/project/<int:project_id>/google/check-auth', views_import.check_google_auth, name='check_google_auth'),
    path('api/project/<int:project_id>/google/docs', views_import.list_google_docs_view, name='list_google_docs'),
    path('api/project/<int:project_id>/google/import', views_import.start_google_import, name='start_google_import'),
    path('api/project/<int:project_id>/google/import/status', views_import.import_status, name='import_status'),
    path('api/project/<int:project_id>/google/import/retry', views_import.retry_import, name='retry_import'),
    path('500/', lambda r: 1/0),
    path('error/400/', views.error_400, name='error_400'),
    path('error/401/', views.error_401, name='error_401'),
    path('error/403/', views.error_403, name='error_403'),
    path('error/404/', views.error_404, name='error_404'),
    path('error/408/', views.error_408, name='error_408'),
    path('error/413/', views.error_413, name='error_413'),
    path('error/429/', views.error_429, name='error_429'),
    path('error/500/', views.error_500, name='error_500'),
    path('error/502/', views.error_502, name='error_502'),
    path('error/503/', views.error_503, name='error_503'),
]