from django.urls import path, include
from . import views
from . import views_admin


urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('setup/', views.setup, name='setup'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('accounts/', include('allauth.urls')),
    path('changeroles/', views.change_roles, name='change_roles'),
    path('about/', views.about, name='about'),
    path('collaborations/', views.collaborations, name='collaborations'),
    path('deleteproject/', views.delete_project, name='delete_project'),
    path('handlepending/', views.handle_pending, name='handle_pending'),
    path('', include('django_prometheus.urls')),
    path('docs/', views.docs, name='docs'),
    path('changelog/', views.changelog, name='changelog'),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('addpeople/', views.add_people, name='add_people'),
    path('deleteuser/', views.deleteuser, name='deleteuser'),
    path('revert/', views.revert, name='revert'),
    path('logout/', views.logout, name='logout'),
    path('create-checkout-session/', views.create_checkout_session, name='create-checkout-session'),
    path('success/', views.success, name='success'),
    path('buy/', views.buy, name='buy'),
    path('gen/token', views.get_oauth_token, name='generate_token'),
    path('gen/editor/token', views.generate_editor_token, name='generate_token_editor'),
    path('webhook/stripe/', views.stripe_webhook, name='stripe_webhook'),
    path('api/project/<int:project_id>/documents', views.get_documents, name='get_documents'),
    path('api/project/<int:project_id>/documents/<int:doc_id>', views.get_document, name='get_document'),
    path('api/project/<int:project_id>/documents/add', views.add_document, name='add_document'),
    path('api/project/<int:project_id>/documents/<int:doc_id>/save', views.save_document, name='save_document'),
    path('api/project/<int:project_id>/documents/<int:doc_id>/rename', views.rename_document, name='rename_document'),
    path('api/project/<int:project_id>/documents/<int:doc_id>/delete', views.delete_document, name='delete_document'),
    path('api/project/<int:project_id>/teams', views.get_teams, name='get_teams'),
    path('api/project/<int:project_id>/audits', views.get_audits, name='get_audits'),
    path('api/project/<int:project_id>/pending', views.get_pending_edits, name='get_pending_edits'),
    path('api/project/<int:project_id>/pending-actions', views.get_pending_actions, name='get_pending_actions'),
    path('api/project/<int:project_id>/teams/add', views.create_team, name='create_team'),
    path('api/project/<int:project_id>/teams/<int:team_id>/update', views.update_team, name='update_team'),
    path('api/project/<int:project_id>/teams/<int:team_id>/delete', views.delete_team, name='delete_team'),
    path('api/project/<int:project_id>/teams/<int:team_id>/members/add', views.add_team_member, name='add_team_member'),
    path('api/project/<int:project_id>/teams/<int:team_id>/members/remove', views.remove_team_member, name='remove_team_member'),
    path('api/project/<int:project_id>/teams/<int:team_id>/members/role', views.update_team_member_role, name='update_team_member_role'),
    path('api/project/<int:project_id>/teams/<int:team_id>/members/review', views.update_team_member_review, name='update_team_member_review'),
    path('profile/', views.profile, name='profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('cancel-subscription/', views.cancel_subscription, name='cancel_subscription'),
    path('delete-account/', views.delete_account, name='delete_account'),
    path('admin-panel/', views_admin.admin_panel, name='admin_panel'),
    path('admin-panel/update-user/', views_admin.admin_update_user, name='admin_update_user'),
    path('admin-panel/delete-user/', views_admin.admin_delete_user, name='admin_delete_user'),
    path('admin-panel/delete-project/', views_admin.admin_delete_project, name='admin_delete_project'),
    path('admin-panel/add-changelog/', views_admin.admin_add_changelog, name='admin_add_changelog'),
    path('admin-panel/update-changelog/', views_admin.admin_update_changelog, name='admin_update_changelog'),
    path('admin-panel/delete-changelog/', views_admin.admin_delete_changelog, name='admin_delete_changelog'),
]