# k8s/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solaradocs-web
  namespace: solaradocs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: solaradocs-web
  template:
    metadata:
      labels:
        app: solaradocs-web
    spec:
      containers:
        - name: web
          image: solaradocs-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          command: ["gunicorn", "logic.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
          env:
            - name: DEBUG
              value: "True"
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: solaradocs-secrets
                  key: redis-url
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: solaradocs-secrets
                  key: database-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: solaradocs-secrets
                  key: django-secret-key
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi