# k8s/templates/redis.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: solaradocs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server", "--appendonly", "yes", "--requirepass", "Mucia850"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: solaradocs
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379