# k8s/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: solaradocs-secrets
  namespace: solaradocs
type: Opaque
stringData:
  redis-url: "redis://:Mucia850@redis:6379/0"
  database-url: "postgresql://neondb_owner:npg_IitUZ0MDG2pY@ep-old-lab-a2a6arsp-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  django-secret-key: "a05&=f#*h3!0uof^+n48$4)xi!bz@8)+w^tvf1+apk7$1srvkax"