# Generated by Django 4.2.27 on 2026-02-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='action',
            field=models.CharField(default='edit', max_length=90),
        ),
    ]
