# Generated by Django 4.2.27 on 2025-12-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Tier',
            field=models.CharField(default='Free', max_length=10, verbose_name='Tier'),
        ),
    ]
