# Generated by Django 4.2.27 on 2026-02-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0002_alter_audit_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerDocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solaradocs.documents')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solaradocs.project')),
            ],
        ),
    ]
