# Generated by Django 4.2.27 on 2026-01-14 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0002_alter_teams_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='members',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='roles',
        ),
        migrations.AddField(
            model_name='audit',
            name='action',
            field=models.CharField(default='edit', max_length=50),
        ),
        migrations.AlterField(
            model_name='audit',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_audits', to='solaradocs.documents'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EDITOR', 'Editor'), ('ADMIN', 'Admin')], default='EDITOR', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='solaradocs.teams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
