# Generated by Django 4.2.27 on 2026-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0003_remove_teams_members_remove_teams_roles_audit_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='can_direct_save',
            field=models.BooleanField(default=False),
        ),
    ]
