# Generated by Django 4.2.27 on 2026-02-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0004_viewerdocumentaccess_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerdocumentaccess',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_access', to='solaradocs.documents'),
        ),
        migrations.AlterField(
            model_name='viewerdocumentaccess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_document_access', to='solaradocs.project'),
        ),
    ]
