# Generated by Django 4.2.27 on 2026-02-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0005_alter_viewerdocumentaccess_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerdocumentaccess',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solaradocs.documents'),
        ),
        migrations.AlterField(
            model_name='viewerdocumentaccess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solaradocs.project'),
        ),
    ]
