# Generated by Django 4.2.27 on 2026-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0006_add_changelog_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
