# Generated by Django 4.2.27 on 2026-02-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0006_alter_viewerdocumentaccess_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retries_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
