# Generated by Django 4.2.27 on 2026-04-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0007_user_retries_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('personal', 'Personal'), ('team', 'Team'), ('enterprise', 'Enterprise')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('left_uses', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
