# Generated by Django 4.2.27 on 2026-01-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0007_pending_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept', 'Accepted'), ('reject', 'Rejected')], max_length=10)),
                ('document_name', models.CharField(max_length=255)),
                ('pending_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actioned_pendings', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_actions', to='solaradocs.documents')),
                ('pending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_pendings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='solaradocs.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
