# Generated by Django 4.2.27 on 2026-04-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0009_user_promo_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
