# Generated by Django 4.2.27 on 2026-04-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0010_user_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='google_doc_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
