# Generated by Django 4.2.27 on 2026-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0011_documents_google_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaction',
            name='reject_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
