# Generated by Django 4.2.27 on 2026-04-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0012_pendingaction_reject_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaction',
            name='reject_comment',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
