# Generated by Django 4.2.27 on 2026-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0013_alter_pendingaction_reject_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaction',
            name='rejected_content',
            field=models.TextField(blank=True),
        ),
    ]
