# Generated by Django 4.2.27 on 2026-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0014_pendingaction_rejected_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('personal', 'Personal'), ('team', 'Team'), ('enterprise', 'Enterprise')])),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')])),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
