# Generated by Django 4.2.27 on 2026-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaradocs', '0016_rewrite_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='redirect_to_dashboard',
            field=models.BooleanField(default=True, help_text='When true, logged-in users hitting / are redirected to /dashboard/ instead of seeing the landing page.'),
        ),
    ]
